### ISSUE TITLE
滑动屏幕操作，一定要选中一个元素才可以，这样的体验会比较差，可以利用swipe(x,y,xx,yy,duration)脚本应该不需要选中元素，只需要产生脚本运行即

### ISSUE THREAD

**Issue by testwa-leenotes** [testwa/testwa-issue#40]
滑动屏幕操作，一定要选中一个元素才可以，这样的体验会比较差，可以利用swipe(x,y,xx,yy,duration)脚本应该不需要选中元素，只需要产生脚本运行即
可以尝试一下让滑动屏幕录制更简单，目前感觉还是略麻烦

**Comment by xiehuabin** [comment]
1.加sleep在swipe之前；
2.Swipe（x,y,x-end,y-end,duration）
