### ISSUE TITLE
录制界面中， Platform Version，Device Name，Output写成中文 操作系统版本，设备名，输出信息， 结果显示／隐藏

### ISSUE THREAD

**Issue by xiehuabin** [testwa/testwa-issue#7]

**Comment by testwa-leenotes** [comment]
对于录制工具来说，mac版目前相对于appium的原版，体验好了非常多，这和刘新的努力是分不开的；
好的作品需要我们一起加油不断改进体验；
录制工具是一个用户的入口，非常重要，所以类似这个issue所说，建议不用的都可以隐藏，同时去掉尽可能没有多大意义的apiium在界面上的ui的影子，这样是不是体验更好，更能宣传testwa的认知度

**Comment by testwa** [comment]
result不管
